import {bootstrap} from 'bootstrap/dist/css/bootstrap.css'
import '../styles/globals.css'
import Head from "next/head";
import Link from "next/link";
import {TopNavbar} from "../components/top-navbar/top-navbar";
import {useEffect} from "react";
import Script from "next/script";
import {SideNavbar} from "../components/side-navbar/side-navbar";

function MyApp({ Component, pageProps }) {
    useEffect(() => {
        import('bootstrap/dist/js/bootstrap.bundle.min.js');
    }, []);
  return (
      <>
        <Head >
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <title>Token Mint</title>
           <meta name="description" content="Generated by create next app" />
           <link rel="icon" href="/favicon.ico" />

        </Head>
        <TopNavbar/>

        <SideNavbar/>

        <Component {...pageProps} />
      </>
  )
}

export default MyApp
